# Generated by Django 5.1.7 on 2025-03-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=40, unique=True)),
                ('slug', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, max_length=234)),
                ('cat_img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
